services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: aula6-db
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Senh@123
    ports:
      - 1433:1433
    networks:
      - aula6-network

networks:
  aula6-network:
    driver: bridge